name: docmind_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.6


  
  flutter_local_notifications: ^17.0.0
  permission_handler: ^11.0.0
  timezone: ^0.9.2

  
  
  
  local_auth: ^2.3.0              
  flutter_secure_storage: ^9.2.2  # Secure key storage
  encrypt: ^5.0.3                  # AES-256 encryption
  crypto: ^3.0.3                   # SHA-256 hashing
  
 

  fl_chart: ^0.66.0
  uuid: ^4.4.0



  http: ^1.1.0
  shared_preferences: ^2.2.2
  file_picker: ^6.1.1
  speech_to_text: ^6.6.0

  
    
  camera: ^0.10.0
  image: ^4.1.7



  
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^3.0.0


flutter:

  
  uses-material-design: true

  